language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t mjannapureddy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mjannapureddy/docker-react npm run test
